models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from datetime import datetime

db = SQLAlchemy()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)
    posts = db.relationship('PostVideo', backref='user', lazy=True)

    def __str__(self):
        return self.username

class PostVideo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow())
    body = db.Column(db.Text, nullable=False)
    video = db.Column(db.String(200), nullable=False)

    def __str__(self):
        return self.title

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, validators, DateTimeField, TextAreaField, FileField
from datetime import datetime

class LoginForm(FlaskForm):
    username = StringField('Username', [validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired()])
    submit = SubmitField('Login')

class VideoUploadForm(FlaskForm):
    title = StringField("Enter title", [validators.DataRequired()])
    date = DateTimeField("Date", [validators.DataRequired()], default=datetime.now())
    body = TextAreaField("Enter the caption", [validators.DataRequired()])
    video = FileField("select video", [validators.DataRequired()])
    submit = SubmitField("Update", [validators.DataRequired()])

app.py
from flask import Flask, render_template, redirect, send_from_directory, url_for
from forms import LoginForm, VideoUploadForm
from models import User, db, PostVideo
from admin import admin
from flask_login import login_user, login_required, logout_user, LoginManager, current_user
from blueprints import profile

app = Flask(__name__)

app.register_blueprint(profile)

app.secret_key = "1234567890987654321"
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

login_manager = LoginManager(app)
login_manager.login_view = 'login'

db.init_app(app)
admin.init_app(app)

with app.app_context():
    db.create_all()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@app.route('/')
def home():
    return render_template('index.html', user=current_user, videos=PostVideo.query.all())

@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if not user:
            user = User(username=username, password=password)
            db.session.add(user)
            db.session.commit()
        login_user(user)
        return redirect(url_for('home'))
    return render_template('login.html', form=form)

@app.route("/watch/<post_id>")
def get_post(post_id):
    video_post = PostVideo.query.get(post_id)
    return render_template("watch.html", post=video_post)

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

@app.route("/videos/<videoname>")
def send_video(videoname):
    return send_from_directory("videos", videoname)


if __name__ == '__main__':
    app.run(debug=True)

blueprints/__init__.py
from .profile import profile

blueprints/profile.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from forms import LoginForm, VideoUploadForm
from models import db, PostVideo
from werkzeug.utils import secure_filename
import os

profile = Blueprint("Profile", __name__, url_prefix="/profile")

if not os.path.exists("videos"):
    os.makedirs("videos")

if not os.path.exists("images"):
    os.makedirs("images")

@profile.route("/", methods=["GET", "POST"])
@login_required
def profile_page():
    videos = PostVideo.query.all()
    return render_template("profile/profile.html", user=current_user, videos=videos)

@profile.route("/upload", methods=["GET", "POST"])
@login_required
def upload():
    form = VideoUploadForm()
    if form.validate_on_submit():
        video_file = form.video.data
        video_filename = secure_filename(video_file.filename)
        video_file.save(f"videos/{video_filename}")

        new_post = PostVideo(
            user=current_user,
            title=form.title.data,
            body=form.body.data,
            video=video_filename
        )
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for("home"))
    flash("Video uploaded successfully!", "success")
    return render_template('profile/upload.html', user=current_user, form=form)

@profile.route("/edit", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = LoginForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.password = form.password.data
        db.session.commit()
        return redirect(url_for("Profile.profile_page"))
    return render_template("profile/edit.html", user=current_user, form=form)

@profile.route("/delete/<video_id>")
def delete_video(video_id):
    video = PostVideo.query.get_or_404(video_id)
    if video.user_id == current_user.id:
        os.remove(f"videos/{video.video}")
        db.session.delete(video)
        db.session.commit()
        return redirect(url_for("Profile.profile_page"))
    else:
        flash("You are not authorized to delete this video.", "danger")
        return redirect(url_for("Profile.profile_page"))

@profile.route("/edit/<video_id>", methods=["GET", "POST"])
def edit_video(video_id):
    video = PostVideo.query.filter_by(id=video_id).first_or_404()
    if video.user_id == current_user.id:
        form = VideoUploadForm()
        if form.validate_on_submit():
            PostVideo.query.filter_by(id=video_id).update({PostVideo.title: form.title.data, PostVideo.body: form.body.data})
            db.session.commit()
            return redirect(url_for("Profile.profile_page"))
        form.title.data = video.title
        form.body.data = video.body
        return render_template("profile/edit_video.html", user=current_user, form=form, video=video)
    else:
        flash("You are not authorized to edit this video.", "danger")
        return redirect(url_for("Profile.profile_page"))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="website icon" href="{{ url_for('static', filename='metube.jpg') }}">
    <style>
        .video-box {
            display: inline-flex;
        }
    </style>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-DQvkBjpPgn7RC31MCQoOeC9TI2kdqa4+BSgNMNj8v77fdC77Kj5zpWFTJaaAoMbC" crossorigin="anonymous"> -->
</head>
<body>
    <header>
        <div class="container">
            <div class="logo"><h1><a href="#" class="title">MeTube</a></h1></div>
        </div>
        <div class="sections">
            {% if user.is_authenticated %}
                <a href="{{ url_for('Profile.profile_page') }}" class="section">Profile</a>
                <a href="{{ url_for('logout') }}" class="section">Logout</a>
            {% else %}
                <a href="{{ url_for('login') }}" class="section">Login</a>
            {% endif %}
        </div>
    </header>
    <main>
        <div class="video-boxes">
            {% for video in videos %}
                <div class="video-box">
                    <a href="/watch/{{ video.id }}">
                        <video controls src="/videos/{{ video.video }}" width="350" height="250"></video>
                    </a>
                </div>
            {% endfor %}
        </div>
    </main>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-YUe2LzesAfftltw+PEaao2tjU/QATaW/rOitAq67e0CT0Zi2VVRL0oC4+gAaeBKu" crossorigin="anonymous"></script> -->
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | MeTube</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
</head>
<body>
    <div class="wrapper">
        <form action="/login" method="post">
            {{ form.hidden_tag() }}
            {{ form.username.label }}: {{ form.username() }}<br>
            {{ form.password.label }}: {{ form.password() }}<br>
            {{ form.submit() }}
        </form>
    </div>
</body>
</html>

templates/profile/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete |MeTube</title>
</head>
<body>
    {% if post.user_id == current_user.id %}
        
</body>
</html>

templates/profile/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile | MeTube</title>
</head>
<body>
    <form action="/profile/edit" method="post">
        {{ form.hidden_tag() }}
        {{ form.username.label }}: {{ form.username() }}<br>
        {{ form.password.label }}: {{ form.password() }}<br>
        {{ form.submit() }}
    </form>
</body>
</html>

templates/profile/edit_video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Video | MeTube</title>
</head>
<body>
    <form action="{{ url_for('Profile.edit_video', video_id=vide.id) }}" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.title.label }}: {{ form.title() }}<br>
        {{ form.body.label }}: {{ form.body() }}<br>
        {{ form.submit() }}
    </form>
</body>
</html>

templates/profile/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile | MeTube</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header>
        <div class="container">
            <div class="logo"><h1><a href="#" class="title">Hello, {{ user.username }}</a></h1></div>
        </div>
        <div class="sections">
            <a href="{{ url_for('Profile.upload') }}" class="section">Upload</a>
            <a href="{{ url_for('logout') }}" class="section">Logout</a>
            <a href="{{ url_for('Profile.edit_profile') }}" class="section">Edit Profile</a>
        </div>
    </header>
    <main>
        <h1>Your Videos</h1>
        <div class="video-boxes">
            {% for video in videos %}
                {% if video.user_id == user.id %}
                    <div class="video-box">
                        <a href="/watch/{{ video.id }}">
                            <video controls src="/videos/{{ video.video }}" width="400" height="500"></video>
                        </a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </main>
</body>
</html>

templates/profile/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload | MeTube</title>
</head>
<body>
    <form action="/profile/upload" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.title.label }}: {{ form.title }} <br>
        {{ form.date.label }}: {{ form.date }} <br>
        {{ form.body.label }}: {{ form.body }} <br>
        {{ form.video.label }}: {{ form.video }} <br>
        {{ form.submit }}
    </form>
</body>
</html>

templates/watch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Watch | MeTube</title>
    <style>
        * {
            font-family: sans-serif;
        }
        .user-rights a {
            padding: 10px;
        }
    </style>
</head>
<body>
    <video controls src="/videos/{{ post.video }}" width="900" height="600"></video>
    <h1>{{ post.title }}</h1>
    <h3>{{ post.date }}</h3>
    <p>{{ post.body }}</p>
    {% if post.user_id == current_user.id %}
        <div class="user-rights">
            <a href="/profile/delete/{{ post.id }}">Delete</a>
            <a href="/profile/edit/{{ post.id }}">Edit</a>
        </div>
    {% endif %}
    <br>
</body>
</html>